// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/Uncensored-Developer/buzz/internal/config"
	"github.com/Uncensored-Developer/buzz/internal/logger"
	"github.com/Uncensored-Developer/buzz/internal/server"
)

// Injectors from wire.go:

func InitializeServer() (*server.Server, error) {
	configConfig, err := config.LoadConfig()
	if err != nil {
		return nil, err
	}
	zapLogger := logger.NewLogger(configConfig)
	serverServer := server.NewServer(configConfig, zapLogger)
	return serverServer, nil
}
