// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"context"
	"github.com/Uncensored-Developer/buzz/pkg/config"
	"github.com/Uncensored-Developer/buzz/pkg/logger"
	"github.com/Uncensored-Developer/buzz/pkg/testcontainer"
)

// Injectors from wire.go:

func InitializeTestDatabase(ctx context.Context) (*testcontainer.TestDatabase, error) {
	configConfig, err := config.LoadConfig()
	if err != nil {
		return nil, err
	}
	zapLogger := logger.NewLogger(configConfig)
	testDatabase, err := testcontainer.NewTestDatabase(ctx, zapLogger)
	if err != nil {
		return nil, err
	}
	return testDatabase, nil
}
