upstream backend_app {
    server api_1:8003;
    server api_2:8004;
}

server {
    listen 80;
    server_name buzz.app;

    location / {
        proxy_pass http://backend_app;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
